<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Oosgrids;

class OOS extends Model
{
    use HasFactory;

    protected $fillable = [
          'id',
          'Form_type',
          'initiator_id',
          'division_id',
          'record',
          'record_number',
          'intiation_date',
          'initiator',
          'initiator_group',
          'initiator_group_code',
          'due_date',
          'severity_level_gi',
          'initiated_through_gi',
          'if_others_gi',
          'is_repeat_gi',
          'repeat_nature_gi',
          'nature_of_change_gi',
          'deviation_occured_on_gi',
          'description_gi',
          'initial_attachment_gi',
          'reference_system_document_gi',
          'source_document_type_gi',
          'oos_observed_on',
          'delay_justification',
          'oos_reported_date',
          'reason_manufacturing_pii',
          'manufacturing_multi_select',
          'oos_details_obvious_error',
          'immediate_action',
          'reference_document',
          'sample_type_gi',
          'product_material_name_gi',
          'market_gi',
          'specification_details',
          'analyst_interview_pli',
          'Any_other_batches',
          'details_of_trend',
          'root_cause_identified_pia',
          'is_repeat_assingable_pia',
          'repeat_testing_pia',
          'result_of_repeat',
          'impact_assesment_pia',
          'resampling_required_ib',
          'repeat_testing_ib',
          'production_person_ib',
          'escalation_required',
          'notification_ib',
          'justification_ib',
          'checklist_outcome_iia',
          'production_head_person',
          'Summary_Of_Inv_IIB',
          'capa_required_IIB',
          'reference_capa_IIB',
          'resampling_req_IIB',
          'Repeat_testing_IIB',
          'reason_manufacturing_delay',
          'result_of_rep_test_IIB',
          'Any_other_cause',
          'rational_for_assingnable',
          'STP_details',
          'manufacture_vendor',
          'phase_ib_inv_required_plir',
          'phase_iib_inv_required_plir',
          'capa_required_iia',
          'reference_capa_no_iia',
          'hod_remark1',
          'hod_remark2',
          'hod_remark3',
          'hod_remark4',
          'hod_remark5',
          'QA_Head_remark1',
          'QA_Head_remark2',
          'QA_Head_remark3',
          'QA_Head_remark4',
          'QA_Head_remark5',
          'QA_Head_primary_remark1',
          'QA_Head_primary_remark2',
          'assign_cause_found',
          'phase_ib_assi_cause',
          'phase_ii_a_assi_cause',
          'QA_Head_primary_remark3',
          'QA_Head_primary_remark4',
          'QA_Head_primary_remark5',
          'QA_Head_attachment1',
          'QA_Head_attachment2',
          'QA_Head_attachment3',
          'QA_Head_attachment4',
          'QA_Head_attachment5',
          'QA_Head_primary_attachment1',
          'QA_Head_primary_attachment2',
          'QA_Head_primary_attachment3',
          'QA_Head_primary_attachment4',
          'QA_Head_primary_attachment5',
          'provide_attachment1',
          'provide_attachment2',
          'provide_attachment3',
          'provide_attachment4',
          'provide_attachment5',
          'customer_gi',
          'Comments_plidata',
          'checklists',
          'repeat_nature',
          'root_comment',
          'field_alert_required',
          'field_alert_ref_no_pli',
          'justify_if_no_field_alert_pli',
          'verification_analysis_required_pli',
          'verification_analysis_ref_pli',
          'analyst_interview_req_pli',
          'analyst_interview_ref_pli',
          'justify_if_no_analyst_int_pli',
          'phase_i_investigation_required_pli',
          'phase_i_investigation_pli',
          'phase_i_investigation_ref_pli',
          'file_attachments_pli',
          'file_attachments_pII',
          'summary_of_prelim_investiga_plic',
          'root_cause_identified_plic',
          'oos_category_root_cause_ident_plic',
          'oos_category_others_plic',
          'root_cause_details_plic',
          'Description_Deviation',
          'recommended_actions_required_plic',
          'recommended_actions_reference_plic',
          'capa_required_plic',
          'reference_capa_no_plic',
          'delay_justification_for_pi_plic',
          'supporting_attachment_plic',
          'review_comments_plir',
          'phase_ii_inv_required_plir',
          'supporting_attachments_plir',
          'qa_approver_comments_piii',
          'manufact_invest_required_piii',
          'manufacturing_invest_type_piii',
          'manufacturing_invst_ref_piii',
          're_sampling_required_piii',
          'audit_comments_piii',
          're_sampling_ref_no_piii',
          'hypo_exp_required_piii',
          'hypo_exp_reference_piii',
          'attachment_piii',
          'phase_IIB_attachment',
          'summary_of_exp_hyp_piiqcr',
          'summary_mfg_investigation_piiqcr',
          'root_casue_identified_piiqcr',
          'oos_category_reason_identified_piiqcr',
          'others_oos_category_piiqcr',
          'OOS_review_similar',
          'if_others_oos_category',
          'impact_assessment_IIA',
          'phase_ii_inv_req_ib',
          'details_of_root_cause_piiqcr',
          'impact_assessment_piiqcr',
          'recommended_action_required_piiqcr',
          'recommended_action_reference_piiqcr',
          'investi_required_piiqcr',
          'invest_ref_piiqcr',
          'attachments_piiqcr',
          'review_comment_atp',
          'additional_test_proposal_atp',
          'additional_test_reference_atp',
          'any_other_actions_required_atp',
          'action_task_reference_atp',
          'additional_testing_attachment_atp',
          'conclusion_comments_oosc',
          'specification_limit_oosc',
          'results_to_be_reported_oosc',
          'final_reportable_results_oosc',
          'justifi_for_averaging_results_oosc',
          'oos_stands_oosc',
          'capa_req_oosc',
          'capa_ref_no_oosc',
          'Field_alert_QA_initial_approval',
          'justify_if_capa_not_required_oosc',
          'file_attachments_if_any_ooscattach',
          'action_plan_req_oosc',
          'action_plan_ref_oosc',
          'justification_for_delay_oosc',
          'attachments_if_any_oosc',
          'conclusion_review_comments_ocr',
          'action_taken_on_affec_batch_ocr',
          'capa_req_ocr',
          'capa_refer_ocr',
          'req_action_plan_ocr',
          'req_action_task_ocr',
          'action_task_reference_ocr',
          'risk_assessment_req_ocr',
          'justify_if_no_risk_assessment_ocr',
          'conclusion_attachment_ocr',
          'action_on_affected_batch',
          'cq_review_comments_ocqr',
          'capa_required_ocqr',
          'reference_of_capa_ocqr',
          'action_plan_requirement_ocqr',
          'ref_action_plan_ocqr',
          'cq_attachment_ocqr',
          'cq_approver',
          'oos_category_bd',
          'others_bd',
          'material_batch_release_bd',
          'other_action_bd',
          'field_alert_reference_bd',
          'other_parameters_results_bd',
          'trend_of_previous_batches_bd',
          'stability_data_bd',
          'process_validation_data_bd',
          'method_validation_bd',
          'any_market_complaints_bd',
          'statistical_evaluation_bd',
          'risk_analysis_disposition_bd',
          'conclusion_bd',
          'outcome_phase_IA',
          'reason_for_proceeding',
          'summaryy_of_review',
          'Probable_cause_iden',
          'proposal_for_hypothesis_IB',
          'proposal_for_hypothesis_others',
          'details_of_result',
          'Probable_Cause_Identified',
          'Any_other_Comments',
          'Proposal_for_Hypothesis',
          'Summary_of_Hypothesis',
          'Assignable_Cause',
          'Types_of_assignable',
          'Types_of_assignable_others',
          'Evaluation_Timeline',
          'timeline_met',
          'timeline_extension',
          'Repeat_testing_plan',
          'Repeat_analysis_method',
          'Details_repeat_analysis',
          'Impact_assessment1',
          'Conclusion1',
          'CAPA_applicable',
          'Laboratory_Investigation_Hypothesis',
          'Outcome_of_Laboratory',
          'Evaluation_IIB',
          'Assignable_Cause111',
          'If_assignable_cause',
          'If_assignable_error',
          'phase_inves_required_bd',
          'phase_inves_reference_bd',
          'justify_for_delay_in_activity_bd',
          'disposition_attachment_bd',
          'other_action_specify_ro',
          'reopen_attachment_ro',
          'reopen_approval_comments_uaa',
          'addendum_attachment_uaa',
          'execution_comments_uae',
          'action_task_required_uae',
          'action_task_reference_no_uae',
          'addi_testing_req_uae',
          'Addi_testing_ref_uae',
          'investigation_req_uae',
          'investigation_ref_uae',
          'hypo_exp_req_uae',
          'hypo_exp_ref_uae',
          'addendum_attachments_uae',
          'addendum_review_comments_uar',
          'required_attachment_uar',
          'verification_comments_uav',
          'verification_attachment_uar',
          'hod_attachment1',
          'hod_attachment2',
          'hod_attachment3',
          'hod_attachment4',
          'hod_attachment5',
          'status',
          'stage',
          // 'type',
          'date_open',
          'date_close'
      ];

    protected $casts = [
      'proposal_for_hypothesis_IB' => 'array',
      'recommended_actions_reference_plic' => 'array',
      'reference_document' => 'array',
      'Comments_plidata' => 'array',
      'verification_analysis_ref_pli' => 'array',
      'analyst_interview_ref_pli' => 'array',
      'justify_if_no_analyst_int_pli' => 'array',
      'summary_of_prelim_investiga_plic' => 'array',
      'oos_category_others_plic' => 'array',
      'Description_Deviation' => 'array',
      'qa_approver_comments_piii'=>'array',
      'manufacturing_invst_ref_piii' => 'array',
      'summary_mfg_investigation_piiqcr' => 'array',
      'details_of_root_cause_piiqcr' => 'array',
      'recommended_action_reference_piiqcr' => 'array',
      'invest_ref_piiqcr' => 'array',
      'checklists' => 'array',
      'action_plan_ref_oosc' => 'array',
      'capa_refer_ocr' => 'array',
      'action_task_reference_ocr' => 'array',
      'risk_assessment_ref_ocr' => 'array',
      'field_alert_reference_bd' => 'array',
      'phase_inves_reference_bd' => 'array',
      'action_task_reference_no_uae' => 'array',
      'Addi_testing_ref_uae' => 'array',
      'investigation_ref_uae' => 'array',
      'hypo_exp_ref_uae' => 'array',
      'initial_attachment_gi' => 'array',
      'file_attachments_pli' => 'array',
      'file_attachments_pII' => 'array',
      'supporting_attachment_plic' => 'array',
      'supporting_attachments_plir' => 'array',
      'attachments_piiqcr' => 'array',
      'additional_testing_attachment_atp' => 'array',
      'file_attachments_if_any_ooscattach' => 'array',
      'conclusion_attachment_ocr' => 'array',
      'cq_attachment_ocqr' => 'array',
      'disposition_attachment_bd' => 'array',
      'reopen_attachment_ro' => 'array',
      'addendum_attachment_uaa' => 'array',
      'addendum_attachments_uae' => 'array',
      'required_attachment_uar' => 'array',
      'hod_attachment1' => 'array',
      'hod_attachment2' => 'array',
      'hod_attachment3' => 'array',
      'hod_attachment4' => 'array',
      'hod_attachment5' => 'array',
      'QA_Head_attachment1' => 'array',
      'QA_Head_attachment2' => 'array',
      'QA_Head_attachment3' => 'array',
      'QA_Head_attachment4' => 'array',
      'QA_Head_attachment5' => 'array',
      'QA_Head_primary_attachment1' => 'array',
      'QA_Head_primary_attachment2' => 'array',
      'QA_Head_primary_attachment3' => 'array',
      'QA_Head_primary_attachment4' => 'array',
      'QA_Head_primary_attachment5' => 'array',
      'provide_attachment1' => 'array',
          'provide_attachment2' => 'array',
          'provide_attachment3' => 'array',
          'provide_attachment4' => 'array',
          'provide_attachment5' => 'array',
          'phase_IIB_attachment' => 'array',
      // 'file_attachments_if_any_ooscattach' => 'array',
      'verification_attachment_uar' => 'array',
    ];

    public function grids()
    {
      return $this->hasMany(Oosgrids::class, 'oos_id');
    }
    public function record_number()
    {
        return $this->morphOne(QmsRecordNumber::class, 'recordable');
    }
}
