<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Oosgrids;

class OOS extends Model
{
    use HasFactory;

    protected $fillable = [
          'id',
          'initiator_id',
          'division_id',
          'record_number',
          'intiation_date',
          'initiator',
          'initiator_group',
          'initiator_group_code',
          'due_date',
          'severity_level_gi',
          'initiated_through_gi',
          'if_others_gi',
          'is_repeat_gi',
          'repeat_nature_gi',
          'nature_of_change_gi',
          'deviation_occured_on_gi',
          'description_gi',
          'initial_attachment_gi',
          'reference_system_document_gi',
          'source_document_type_gi',
          'reference_document',
          'sample_type_gi',
          'product_material_name_gi',
          'market_gi',
          'customer_gi',
          'Comments_plidata',
          'field_alert_required',
          'field_alert_ref_no_pli',
          'justify_if_no_field_alert_pli',
          'verification_analysis_required_pli',
          'verification_analysis_ref_pli',
          'analyst_interview_req_pli',
          'analyst_interview_ref_pli',
          'justify_if_no_analyst_int_pli',
          'phase_i_investigation_required_pli',
          'phase_i_investigation_pli',
          'phase_i_investigation_ref_pli',
          'file_attachments_pli',
          'file_attachments_pII',
          'summary_of_prelim_investiga_plic',
          'root_cause_identified_plic',
          'oos_category_root_cause_ident_plic',
          'oos_category_others_plic',
          'root_cause_details_plic',
          'Description_Deviation',
          'recommended_actions_required_plic',
          'recommended_actions_reference_plic',
          'capa_required_plic',
          'reference_capa_no_plic',
          'delay_justification_for_pi_plic',
          'supporting_attachment_plic',
          'review_comments_plir',
          'phase_ii_inv_required_plir',
          'supporting_attachments_plir',
          'qa_approver_comments_piii',
          'manufact_invest_required_piii',
          'manufacturing_invest_type_piii',
          'manufacturing_invst_ref_piii',
          're_sampling_required_piii',
          'audit_comments_piii',
          're_sampling_ref_no_piii',
          'hypo_exp_required_piii',
          'hypo_exp_reference_piii',
          'attachment_piii',
          'summary_of_exp_hyp_piiqcr',
          'summary_mfg_investigation_piiqcr',
          'root_casue_identified_piiqcr',
          'oos_category_reason_identified_piiqcr',
          'others_oos_category_piiqcr',
          'details_of_root_cause_piiqcr',
          'impact_assessment_piiqcr',
          'recommended_action_required_piiqcr',
          'recommended_action_reference_piiqcr',
          'investi_required_piiqcr',
          'invest_ref_piiqcr',
          'attachments_piiqcr',
          'review_comment_atp',
          'additional_test_proposal_atp',
          'additional_test_reference_atp',
          'any_other_actions_required_atp',
          'action_task_reference_atp',
          'additional_testing_attachment_atp',
          'conclusion_comments_oosc',
          'specification_limit_oosc',
          'results_to_be_reported_oosc',
          'final_reportable_results_oosc',
          'justifi_for_averaging_results_oosc',
          'oos_stands_oosc',
          'capa_req_oosc',
          'capa_ref_no_oosc',
          'justify_if_capa_not_required_oosc',
          'file_attachments_if_any_ooscattach',
          'action_plan_req_oosc',
          'action_plan_ref_oosc',
          'justification_for_delay_oosc',
          'attachments_if_any_oosc',
          'conclusion_review_comments_ocr',
          'action_taken_on_affec_batch_ocr',
          'capa_req_ocr',
          'capa_refer_ocr',
          'req_action_plan_ocr',
          'req_action_task_ocr',
          'action_task_reference_ocr',
          'risk_assessment_req_ocr',
          'justify_if_no_risk_assessment_ocr',
          'conclusion_attachment_ocr',
          'cq_review_comments_ocqr',
          'capa_required_ocqr',
          'reference_of_capa_ocqr',
          'action_plan_requirement_ocqr',
          'ref_action_plan_ocqr',
          'cq_attachment_ocqr',
          'cq_approver',
          'oos_category_bd',
          'others_bd',
          'material_batch_release_bd',
          'other_action_bd',
          'field_alert_reference_bd',
          'other_parameters_results_bd',
          'trend_of_previous_batches_bd',
          'stability_data_bd',
          'process_validation_data_bd',
          'method_validation_bd',
          'any_market_complaints_bd',
          'statistical_evaluation_bd',
          'risk_analysis_disposition_bd',
          'conclusion_bd',
          'phase_inves_required_bd',
          'phase_inves_reference_bd',
          'justify_for_delay_in_activity_bd',
          'disposition_attachment_bd',
          'other_action_specify_ro',
          'reopen_attachment_ro',
          'reopen_approval_comments_uaa',
          'addendum_attachment_uaa',
          'execution_comments_uae',
          'action_task_required_uae',
          'action_task_reference_no_uae',
          'addi_testing_req_uae',
          'Addi_testing_ref_uae',
          'investigation_req_uae',
          'investigation_ref_uae',
          'hypo_exp_req_uae',
          'hypo_exp_ref_uae',
          'addendum_attachments_uae',
          'addendum_review_comments_uar',
          'required_attachment_uar',
          'verification_comments_uav',
          'verification_attachment_uar',
          'status',
          'stage',
          // 'type',
          'date_open',
          'date_close'
      ];

    protected $casts = [
      'recommended_actions_reference_plic' => 'array',
      'reference_document' => 'array',
      'Comments_plidata' => 'array',
      'verification_analysis_ref_pli' => 'array',
      'analyst_interview_ref_pli' => 'array',
      'justify_if_no_analyst_int_pli' => 'array',
      'summary_of_prelim_investiga_plic' => 'array',
      'oos_category_others_plic' => 'array',
      'Description_Deviation' => 'array',
      'qa_approver_comments_piii'=>'array',
      'manufacturing_invst_ref_piii' => 'array',
      'summary_mfg_investigation_piiqcr' => 'array',
      'details_of_root_cause_piiqcr' => 'array',
      'recommended_action_reference_piiqcr' => 'array',
      'invest_ref_piiqcr' => 'array',
      // 'additional_test_reference_atp' => 'array',
      'action_plan_ref_oosc' => 'array',
      'capa_refer_ocr' => 'array',
      'action_task_reference_ocr' => 'array',
      'risk_assessment_ref_ocr' => 'array',
      'field_alert_reference_bd' => 'array',
      'phase_inves_reference_bd' => 'array',
      'action_task_reference_no_uae' => 'array',
      'Addi_testing_ref_uae' => 'array',
      'investigation_ref_uae' => 'array',
      'hypo_exp_ref_uae' => 'array',
      'initial_attachment_gi' => 'array',
      'file_attachments_pli' => 'array',
      'file_attachments_pII' => 'array',
      'supporting_attachment_plic' => 'array',
      'supporting_attachments_plir' => 'array',
      'attachments_piiqcr' => 'array',
      'additional_testing_attachment_atp' => 'array',
      'file_attachments_if_any_ooscattach' => 'array',
      'conclusion_attachment_ocr' => 'array',
      'cq_attachment_ocqr' => 'array',
      'disposition_attachment_bd' => 'array',
      'reopen_attachment_ro' => 'array',
      'addendum_attachment_uaa' => 'array',
      'addendum_attachments_uae' => 'array',
      'required_attachment_uar' => 'array',
      'file_attachments_if_any_ooscattach' => 'array',
      'verification_attachment_uar' => 'array'
    ];

    public function grids()
    {
      return $this->hasMany(Oosgrids::class, 'oos_id');
    }
    public function record_number()
    {
        return $this->morphOne(QmsRecordNumber::class, 'recordable');
    }
}
