<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OOS_micro extends Model
{
    use HasFactory;

    protected $table = 'o_o_s__micros';

    public function grids()
    {
        return $this->hasMany(OOS_Micro_grid::class, 'oos_micro_id', 'id');
    }

    public function record_number()
    {
        return $this->morphOne(QmsRecordNumber::class, 'recordable');
    }

    protected $fillable = [
        'record',
        'form_type',
        'division_id',
        'initiator_id',
        'intiation_date',
        'due_date',
        'description_gi',
        'severity_level_gi',
        'initiator_group_gi',
        'initiator_group_code_gi',
        'initiated_through_gi',
        'if_others_gi',
        'is_repeat_gi',
        'repeat_nature_gi',
        'nature_of_change_gi',
        'deviation_occured_on_gi',
        'source_document_type_gi',
        'reference_system_document_gi',
        'reference_document_gi',
        'sample_type_gi',
        'product_material_name_gi',
        'market_gi',
        'customer_gi',
        'comments_pli',
        'field_alert_required_pli',
        'field_alert_ref_no_pli',
        'justify_if_no_field_alert_pli',
        'verification_analysis_required_pli',
        'verification_analysis_ref_pli',
        'analyst_interview_req_pli',
        'analyst_interview_ref_pli',
        'justify_if_no_analyst_int_pli',
        'phase_i_investigation_required_pli',
        'phase_i_investigation_pli',
        'phase_i_investigation_ref_pli',
        'summary_of_prelim_investiga_plic',
        'root_cause_identified_plic',
        'oos_category_root_cause_ident_plic',
        'oos_category_others_plic',
        'root_cause_details_plic',
        'oos_category_root_cause_plic',
        'recommended_actions_required_plic',
        'recommended_actions_reference_plic',
        'capa_required_plic',
        'reference_capa_no_plic',
        'delay_justification_for_pi_plic',
        'review_comments_plir',
        'phase_ii_inv_required_plir',
        'qa_approver_comments_piii',
        'manufact_invest_required_piii',
        'manufacturing_invest_type_piii',
        'manufacturing_invst_ref_piii',
        're_sampling_required_piii',
        'audit_comments_piii',
        're_sampling_ref_no_piii',
        'hypo_exp_required_piii',
        'hypo_exp_reference_piii',
        'summary_of_exp_hyp_piiqcr',
        'summary_mfg_investigation_piiqcr',
        'root_casue_identified_piiqcr',
        'oos_category_reason_identified_piiqcr',
        'others_oos_category_piiqcr',
        'details_of_root_cause_piiqcr',
        'impact_assessment_piiqc',
        'impact_assessment_piiqcr',
        'recommended_action_required_piiqcr',
        'recommended_action_reference_piiqcr',
        'investi_required_piiqcr',
        'invest_ref_piiqcr',
        'review_comment_atp',
        'additional_test_proposal_atp',
        'additional_test_reference_atp',
        'any_other_actions_required_atp',
        'action_task_reference_atp',
        'conclusion_comments_oosc',
        'specification_limit_oosc',
        'results_to_be_reported_oosc',
        'final_reportable_results_oosc',
        'justifi_for_averaging_results_oosc',
        'oos_stands_oosc',
        'capa_req_oosc',
        'capa_ref_no_oosc',
        'justify_if_capa_not_required_oosc',
        'action_plan_req_oosc',
        'action_plan_ref_oosc',
        'justification_for_delay_oosc',
        'conclusion_review_comments_ocr',
        'action_taken_on_affec_batch_ocr',
        'capa_req_ocr',
        'capa_refer_ocr',
        'required_action_plan_ocr',
        'required_action_task_ocr',
        'action_task_reference_ocr',
        'risk_assessment_req_ocr',
        'risk_assessment_ref_ocr',
        'justify_if_no_risk_assessment_ocr',
        'qa_approver_ocr',
        'capa_required_OOS_CQ',
        'ref_action_plan_OOS_CQ',
        'reference_of_capa_OOS_CQ',
        'cq_review_comments_OOS_CQ',
        'action_plan_requirement_OOS_CQ',
        'oos_category_BI',
        'others_BI',
        'material_batch_release_BI',
        'other_action_BI',
        'field_alert_reference_BI',
        'other_parameter_result_BI',
        'trend_of_previous_batches_BI',
        'stability_data_BI',
        'process_validation_data_BI',
        'method_validation_BI',
        'any_market_complaints_BI',
        'statistical_evaluation_BI',
        'risk_analysis_for_disposition_BI',
        'conclusion_BI',
        'phase_III_inves_required_BI',
        'phase_III_inves_reference_BI',
        'justify_for_delay_BI',
        'reopen_request',
        //  ======= File Attechment ==========
        'initial_attachment_gi',
        'file_attachments_pli',
        'supporting_attachment_plic',
        'supporting_attachments_plir',
        'attachment_piii',
        'attachments_piiqcr',
        'additional_testing_attachment_atp',
        'attachments_if_any_oosc',
        'conclusion_attachment_ocr',
        'cq_attachment_OOS_CQ',
        'disposition_attachment_BI',
        'reopen_attachment',
        'ua_approval_attachment',
        'ua_Execution_attachments',
        'uar_required_attachment',
        'uav_verification_attachment',
        'attachment_details_cibet',
        'attachment_details_cis',
        'attachment_details_cimlbwt',
        'attachment_details_cima',
        'attachment_details_ciem',
        'attachment_details_cimst',
        // extra field
        'Description_Deviation',
        'action_task_required',
        'action_task_reference_no',
        'addendum_review_comments',
        'reopen_approval_comments',
        'verification_comments',
        'addi_testing_ref',
        'investigation_ref',
        'hypo_exp_ref',

        'status',
        'stage',
        'date_open',
        'date_close',
        'type',
        'parent_record'
    ];

    protected $casts = [
        'hypo_exp_ref' => 'array',
        'investigation_ref' => 'array',
        'addi_testing_ref' => 'array',
        'action_task_reference_no' => 'array',
        'field_alert_ref_no_pli' => 'array',
        'verification_analysis_ref_pli' => 'array',
        'analyst_interview_ref_pli' => 'array',
        'reference_system_document_gi' => 'array',
        'recommended_actions_reference_plic' => 'array',
        // ======== add new type casting =========
        'reference_document_gi' => 'array',
        'manufacturing_invest_type_piii' => 'array',
        'manufacturing_invst_ref_piii' => 'array',
        'phase_i_investigation_ref_pli' =>'array',
        're_sampling_ref_no_piii' => 'array',
        'hypo_exp_reference_piii' => 'array',
        'recommended_action_reference_piiqcr' => 'array',
        'invest_ref_piiqcr' => 'array',
        'additional_test_reference_atp' => 'array',
        'action_task_reference_atp' => 'array',
        'capa_ref_no_oosc' => 'array',
        'action_plan_ref_oosc' => 'array',
        'capa_refer_ocr' => 'array',
        'action_task_reference_ocr' => 'array',
        'risk_assessment_ref_ocr' => 'array',
        'field_alert_reference_BI' => 'array',
        'phase_III_inves_reference_BI' => 'array',
        // ====== attechment =========
        'initial_attachment_gi' => 'array',
        'file_attachments_pli' => 'array',
        'supporting_attachment_plic' => 'array',
        'supporting_attachments_plir' => 'array',
        'attachment_piii' => 'array',
        'attachments_piiqcr' => 'array',
        'additional_testing_attachment_atp' => 'array',
        'attachments_if_any_oosc' => 'array',
        'conclusion_attachment_ocr' => 'array',
        'cq_attachment_OOS_CQ' => 'array',
        'disposition_attachment_BI' => 'array',
        'reopen_attachment' => 'array',
        'ua_approval_attachment' => 'array',
        'ua_Execution_attachments' => 'array',
        'uar_required_attachment' => 'array',
        'uav_verification_attachment' => 'array',
        'attachment_details_cibet' => 'array',
        'attachment_details_cis' => 'array',
        'attachment_details_cimlbwt' => 'array',
        'attachment_details_cima' => 'array',
        'attachment_details_ciem' => 'array',
        'attachment_details_cimst' => 'array'
        

    ];

}

