<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OOT extends Model
{
    use HasFactory;
    protected $fillable = [
        'initiator_id',
        'division_id',
        'record_number',
        'intiation_date',
        'initiator_group',
        'initiator_group_code',
        'due_date',
        'severity_level',
        'initiated_through',
        'if_others',
        'is_repeat',
        'repeat_nature',
        'closure_attachment',
        'deviation_occured_on',
        'description_closure_attachment',
        'initial_attachment',
        'source_document',
        'reference_record',
        'reference_document',
        'product_material_name',
        'grade_typeofwater',
        'sample_locationpoint',
        'market',
        'customer',
        'analyst_name',
        'sample_type',
        'others_specify',
        'stability_for',
        'specification_procedure_no',
        'specification_limit',
        'gi_attachment',
        'upl_comments',
        'verification_analysis_required',
        'upl_refrence_record',
        'upl_anlyst_interview',
        'analyst_interview_ref',
        'justi_if_no_analyst',
        'phase_invest_required',
        'phase_investigation',
        'phase_invest_ref',
        'upli_attachment',
        'summary_preliminary_investigation',
        'root_cause_identified',
        'oot_category_root',
        'soot_category',
        'root_cause_details',
        'impact_of_root_cause',
        'recommended_action_req',
        'recommend_action_refre',
        'capa_required',
        'capa_refrence_no',
        'delay_justification',
        'conclusionattachment',
        'review_comment',
        'capa_review',
        'capa_refrence_review',
        'plir_attachment',
        'qa_approver_report',
        'manufacture_invest',
        'manufacturing_invest',
        'manufacturing_invest_ref',
        're_sampling_required',
        're_sampling_ref_no',
        'hypo_required',
        'hypo_expo_ref',
        'phase_inv_attachment',
        'summary_ofexp',
        'summary_manuf_invest',
        'root_cause_qcreview',
        'oot_category_qcreview',
        'ott_category_others',
        'qcroot_details',
        'qcreview_impactassessment',
        'qcr_recommend_action',
        'qcr_action_refrence',
        'qcr_investigation_req',
        'qcr_invest_refrence',
        'qcr_justify_required',
        'qcr_attachment',
        'atp_review_comment',
        'atp_add_test_proposal',
        'atp_add_test_ref',
        'atp_any_action_req',
        'atp_action_task_ref',
        'atp_attachment',
        'summary_of_OOT_test_results_oot_c',
        'trend_limit_oot_c',
        'oot_stands_oot_c',
        'result_to_be_reported_oot_c',
        'reporting_results_oot_c',
        'capa_required_oot_c',
        'capa_reference_no_oot_c',
        'action_plan_required_oot_c',
        'action_plan_reference_oot_c',
        'justification_for_delay_oot_c',
        'conclusion_review_comments_oot_cr',
        'attachment_if_any_oot_c',
        'capa_required_oot_cr',
        'required_action_plan_oot_cr',
        'capa_reference_oot_cr',
        'action_task_required_oot_cr',
        'reference_record_plan_oot_cr',
        'risk_assessment_required_oot_cr',
        'action_task_reference_oot_cr',
        'risk_assessment_reference_oot_cr',
        'file_attachment_oot_cr',
        'cq_review_comments_oot_cq_r',
        'capa_requirement_oot_cq_r',
        'reference_of_capa_oot_cq_r',
        'action_plan_requirement_oot_cq_r',
        'reference_action_plan_oot_cq_r',
        'qa_attachment_oot_cq_r',
        'disposition_comments_bd',
        'oot_category_bd',
        'others_bd',
        'material_batch_release_bd',
        'conclusion_bd',
        'justify_for_delay_in_activity_bd',
        'file_attachment_bd',
        'reason_for_reopen_re',
        'reopen_attachment_re',
        'approval_comments_uaa',
        'approval_attachment_uaa',
        'execution_comments_uae',
        'action_task_required_uae',
        'action_task_reference_uae',
        'add_testing_required_uae',
        'add_testing_reference_uae',
        'investigation_requirement_uae',
        'investigation_reference_uae',
        'hypothesis_experiment_requirement_uae',
        'hypothesis_experiment_reference_uae',
        'any_attachment_uae',
        'addendum_review_comments_uar',
        'required_attachment_uar',
        'verification_comments_uav',
        'verification_attachment_uav'
    ];

    protected $casts =
    [
    
        
        'reference_record'=>'array',
        'sample_type'=>'array',
        'stability_for'=>'array',
        'gi_attachment'=>'array',
        'upl_refrence_record'=>'array',
        'analyst_interview_ref'=>'array',
        'phase_invest_ref'=>'array',
        'upli_attachment'=>'array',
        'recommend_action_refre'=>'array',
        'capa_refrence_no'=>'array',
        'conclusionattachment'=>'array',
        'capa_refrence_review'=>'array',
        'plir_attachment'=>'array',
        'manufacturing_invest'=>'array',
        'manufacturing_invest_ref'=>'array',
        're_sampling_ref_no'=>'array',
        'hypo_expo_ref'=>'array',
        'phase_inv_attachment'=>'array',
        'qcr_action_refrence'=>'array',
        'qcr_invest_refrence'=>'array',
        'qcr_attachment'=>'array',
        'atp_add_test_ref'=>'array',
        'atp_action_task_ref'=>'array',
        'atp_attachment'=>'array',
        'capa_reference_no_oot_c'=>'array',
        'action_plan_reference_oot_c'=>'array',
        'attachment_if_any_oot_c'=>'array',
        'capa_reference_oot_cr'=>'array',
        'reference_record_plan_oot_cr'=>'array',
        'action_task_reference_oot_cr'=>'array',
        'risk_assessment_reference_oot_cr'=>'array',
        'file_attachment_oot_cr'=>'array',
        'cq_approver_oot_cr'=>'array',
        'reference_of_capa_oot_cq_r'=>'array',
        'reference_action_plan_oot_cq_r'=>'array',
        'qa_attachment_oot_cq_r'=>'array',
        'file_attachment_bd'=>'array',
        'reopen_attachment_re'=>'array',
        'approval_attachment_uaa'=>'array',
        'action_task_reference_uae'=>'array',
        'investigation_reference_uae'=>'array',
        'hypothesis_experiment_reference_uae'=>'array',
        'any_attachment_uae'=>'array',
        'required_attachment_uar'=>'array',
        'verification_attachment_uav'=>'array',







    ];
    
}
